# Generated by Django 4.0.5 on 2023-07-10 06:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.IntegerField(primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.channel')),
            ],
        ),
    ]
